# Railway Backend Configuration
[build]
  builder = "NIXPACKS"
  buildCommand = "npm install"

[deploy]  
  startCommand = "npm start"
  healthcheckPath = "/"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[env]
  NODE_ENV = "production"
  PORT = { default = "5000" }